{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "service-router-operator.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-router-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "service-router-operator.selectorLabels" . | nindent 6 }}
{{- end }}
