# permissions for end users to view dnsconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dnsconfiguration-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: service-router-operator
    app.kubernetes.io/part-of: service-router-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsconfiguration-viewer-role
rules:
- apiGroups:
  - cluster.router.io
  resources:
  - dnsconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.router.io
  resources:
  - dnsconfigurations/status
  verbs:
  - get
