# permissions for end users to edit serviceroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceroute-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: service-router-operator
    app.kubernetes.io/part-of: service-router-operator
    app.kubernetes.io/managed-by: kustomize
  name: serviceroute-editor-role
rules:
- apiGroups:
  - routing.router.io
  resources:
  - serviceroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routing.router.io
  resources:
  - serviceroutes/status
  verbs:
  - get
