# permissions for end users to view dnspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dnspolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: service-router-operator
    app.kubernetes.io/part-of: service-router-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnspolicy-viewer-role
rules:
- apiGroups:
  - router.router.io
  resources:
  - dnspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - router.router.io
  resources:
  - dnspolicies/status
  verbs:
  - get
